language: node_js
node_js:
- 7.4.0
notifications:
  email: false
env:
  global:
  - NODE_ENV: test
before_install:
- npm install -g bower@1.8.0
- npm install -g gulp@3.9.1
- npm install -g karma-cli
- npm install -g protractor@5.1.1
- webdriver-manager update
- bower install
before_script:
- node server &
- sleep 10
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- gulp
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: VMnSrcDuzc+wtoxQdFGrj7r0UCvQ5x+nwRMcId6MTn6kBbs2/ZCNZAnel47sh32DzYLn4Om7hzZDFpLmJZ+SUETFN6XxjTndHH8pV4Nld1N1KX20KNlhpET6m9jcajKjNH6AZf+rCdda7apoBgedp7eAEWW53LcwsRv7RdPZUUiUe/XNP2AgVJuGmHH3teMTqF2yVjr5y0grHhMxhuDYIYz+pKE8YexwukBBYKMqNIkRjKNVuRs9ki3kK81fGrkXQaozewuYpxASxbM+KOc7wbWQRXhO2MQB+2dTP+4BJJwa5I8ePAguxPcx3PQG5KfhxkDcwgfgy0X/meHstmAY2prQS4pRylOe0ywVc6vLKpqbNtVQFfKyeTFrwVpVBgT5rrm0wDE83n/uS1TRWE5GOQ27m7c8Y8kVztIiK/QY+H9YJMmkkSaqawB8khBfbTvIFrBJq3y9jL3dIiOLdokGfWZvj5dMDNVo9YW4edC/i80ezXpSZBXwjqQuG7NnyC5iZWfWMZRrv5ygP5kuFVnz5aszJw/ImlXLf61vHJoQPkXd5EHGFNS28aIbp5qH3IOMB0aW+QY9LNSX3ud0mOwy7281xOMTkDlhqwoK+gAQmdiWA0NN0bJ0LCB19uFGBnmAT06obOZD3tUHyb1CdbRrq8Xm8NlszsWVqRCoz+3K7tw=
  app: weatherconditions
  on:
    repo: dhiegohenrique/exercise3-node
