language: node_js
node_js:
- 7.4.0
notifications:
  email: false
env:
  global:
  - NODE_ENV: test
before_install:
- npm install -g bower@1.8.0
- npm install -g gulp@3.9.1
- npm install -g karma-cli
- npm install -g protractor@5.1.1
- webdriver-manager update
- bower install
before_script:
- node server &
- sleep 10
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- gulp
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: xJfv1Qx9O13acjpVI0od79Vcr7FVxIcfqVbvcGZcB6eM0E48kCS5/VlvHmYLPp27MF+x7uUGCvkguaTow7qc1yomWPfE9eJ/FF9hz7mulSbD8C///Msav+Rn4+e4ynsTGKU1iYWX+sMGuvnsEbDrTF9VAVbxOEG4WPl5iI35S1B376TbOkhWA/A5LR5tEcyVZ2qo2ceLNW38iHEswre4YSQLbqSEgUnNejTqmGVFudOFQgifYa6209laxh57mLTAjVJ+zrW3VoMHDQe5muNfPN0hVlSXjXTYHMtYK8kwH1frfN/h6tRsb3OkkMryIDaoKe79W0F8BobhcylqArM1VA9b52kiupIZFCrer3Sl2h2PUrl/GCwua1YahZCcEk1pytqvA2pEGsuylO84zjkCBLVqb6djBdtz6621NYWKvJtUSrhLFdLu/GTFG9OMhwQbZexJ9HfZWkDuYHTvEHY+73fM1URXW3Ge6MA+NKwnV2/HH5iagVF9AoMQc/HPZFiOGmmWYDcRMUF6fAxMBdSPgX78b5HBVcyHF5f3VnG6sg0v/l2eBqk5t1sDzmxKUtZ+fV/HMDb4Pvs/RQrNaSmIDQsf0HpbFF0t0xXuZcfzOpIMv4yziD7UQmzWI+9pbF61M7EkTY6cYOf6xIAmTTWdX5nBgfjLCrtpz3RN8gyDSUQ=
