language: node_js
node_js:
- 7.4.0
notifications:
  email: false
env:
  global:
  - NODE_ENV: test
before_install:
- npm install -g bower@1.8.0
- npm install -g gulp@3.9.1
- npm install -g karma-cli
- npm install -g protractor@5.1.1
- npm install -g heroku
- webdriver-manager update
- bower install
before_script:
- node server &
- sleep 10
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
# before_deploy:
# - git config --global user.email 'travis@travis-ci.com'
# - git config --global user.name 'Travis CI'
# - git checkout $TRAVIS_BRANCH
# - git add --all
# - git commit -am "Travis commit"
# - gulp
# - cd dist
# - git init
# - git config user.name "dhiegohenrique"
# - git config user.email "dhiego_henrique20@yahoo.com.br"
# - git add .
# - git commit -m "deploy no heroku"
# - wget 0- wget https://toolbelt.heroku.com/install-ubuntu.sh | sh
# - sudo ln -s /usr/local/heroku/bin/heroku /usr/bin/heroku

# - sudo apt-get install software-properties-common # debian only
# - sudo add-apt-repository "deb https://cli-assets.heroku.com/branches/stable/apt ./"
# - curl -L https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
# - sudo apt-get update
# - sudo apt-get install heroku

# - sudo apt-get install ruby-full
# - gem install heroku-api
# - sudo ln -s /usr/local/heroku/bin/heroku /usr/bin/heroku

# - heroku create teste
# - git push heroku master
# before_deploy:
# - gulp
# - cd dist
# - sudo apt-get install -y --force-yes heroku-toolbelt

deploy:
  provider: heroku
  api_key: 5ef56961-7ec5-41ae-84e3-937a2caa4e8d
  app: weatherconditions
  # skip_cleanup: true
#   #file: 'dist/*'
#   #file_glob: true
#   on:
#     repo: dhiegohenrique/exercise3-node
